apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- provider-football-ncaa-worker.yaml
- provider-football-ncaa-ingest.yaml
- provider-football-ncaa-api.yaml
- provider-svc-football-ncaa.yaml
- provider-football-nfl-worker.yaml
- provider-football-nfl-ingest.yaml
- provider-football-nfl-api.yaml
- provider-svc-football-nfl.yaml
- provider-doc-db.yaml
- servicemonitor.yaml
- scaledobject-football-ncaa.yaml
- scaledobject-football-nfl.yaml
- provider-baseball-mlb-worker.yaml
- provider-baseball-mlb-ingest.yaml
- provider-baseball-mlb-api.yaml
- provider-svc-baseball-mlb.yaml
- scaledobject-baseball-mlb.yaml
- provider-ingressroute.yaml
- provider-ingressroute-nfl.yaml
- provider-ingressroute-mlb.yaml