apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- provider-football-ncaa-worker.yaml
- provider-football-ncaa-ingest.yaml
- provider-football-ncaa-api.yaml
- provider-svc-football-ncaa.yaml
- provider-football-nfl-worker.yaml
- provider-football-nfl-ingest.yaml
- provider-football-nfl-api.yaml
- provider-svc-football-nfl.yaml
- provider-doc-db.yaml
- servicemonitor.yaml
- scaledobject.yaml
- provider-ingressroute.yaml