apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-ncaa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-football-ncaa
  template:
    metadata:
      labels:
        app: provider-football-ncaa
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: provider-football-ncaa
        image: sportdeets.azurecr.io/sportsdataprovider:latest
        imagePullPolicy: Always
        command: ["dotnet"]
        args: ["SportsData.Provider.dll", "-mode", "FootballNcaa"]
        env:
          - name: CommonConfig__AzureAppConfigurationConnectionString
            valueFrom:
              secretKeyRef:
                name: azure-app-config
                key: connectionstring
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "1"