apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-ncaa
  namespace: default
  # annotations:
    # TEMP: Disabled during load test to prevent cycling
    # configmap.reloader.stakater.com/reload: "reload-trigger"
spec:
  # replicas managed by KEDA ScaledObject
  selector:
    matchLabels:
      app: provider-football-ncaa
  template:
    metadata:
      labels:
        app: provider-football-ncaa
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: provider-football-ncaa
        image: sportdeets.azurecr.io/sportsdataprovider:1348
        imagePullPolicy: IfNotPresent
        command: ["dotnet"]
        args: ["SportsData.Provider.dll", "-mode", "FootballNcaa"]
        env:
          - name: APPCONFIG_CONNSTR
            valueFrom:
              secretKeyRef:
                name: azure-app-config
                key: connectionstring
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: azure-identity
                key: AZURE_TENANT_ID
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: azure-identity
                key: AZURE_CLIENT_ID
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: azure-identity
                key: AZURE_CLIENT_SECRET
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "1"
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
