apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: provider-football-nfl-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`provider.football-nfl.sportdeets.com`)
      kind: Rule
      services:
        - name: provider-svc-football-nfl
          port: 80
  tls:
    secretName: provider-football-nfl-sportdeets-tls
