apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: provider-football-ncaa-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: provider-football-ncaa
  pollingInterval: 15    # Check every 15 seconds
  cooldownPeriod: 300    # Wait 5 min before scaling down
  minReplicaCount: 0     # Provider calls ESPN - limited to 1 replica for historical sourcing
  maxReplicaCount: 1     # For live season tracking, increase to 4-6
  triggers:
    - type: postgresql
      metadata:
        # Query Hangfire database for pending jobs
        query: >-
          SELECT COUNT(*)::int
          FROM hangfire.jobqueue
          WHERE fetchedat IS NULL
            AND queue = 'default'
        targetQueryValue: "30"                # Scale up if >30 jobs per pod
        activationTargetQueryValue: "1"       # Scale from minReplicas if any jobs
      authenticationRef:
        name: provider-hangfire-trigger-auth
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: provider-hangfire-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: provider-hangfire-pg-params
      key: host
    - parameter: port
      name: provider-hangfire-pg-params
      key: port
    - parameter: userName
      name: provider-hangfire-pg-params
      key: username
    - parameter: password
      name: provider-hangfire-pg-params
      key: password
    - parameter: dbName
      name: provider-hangfire-pg-params
      key: database
    - parameter: sslmode
      name: provider-hangfire-pg-params
      key: sslmode
