apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: provider-metrics
  namespace: default
  labels:
    app: provider-football-ncaa
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - provider-football-ncaa-api
          - provider-football-ncaa-worker
          - provider-football-nfl-api
          - provider-football-nfl-worker
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
