apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  namespace: localdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - name: provider
        image: sportdeets.azurecr.io/sportsdataprovider:353
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      imagePullSecrets:
        - name: sportdeetsacrkey