apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- producer-football-ncaa-worker.yaml
- producer-football-ncaa-ingest.yaml
- producer-football-ncaa-api.yaml
- producer-football-ncaa-service.yaml
- producer-football-nfl-worker.yaml
- producer-football-nfl-ingest.yaml
- producer-football-nfl-api.yaml
- producer-football-nfl-service.yaml
- servicemonitor.yaml
- scaledobject-football-ncaa.yaml
- scaledobject-football-nfl.yaml
- row-count-cronjob.yaml
- producer-baseball-mlb-worker.yaml
- producer-baseball-mlb-ingest.yaml
- producer-baseball-mlb-api.yaml
- producer-baseball-mlb-service.yaml
- scaledobject-baseball-mlb.yaml
- producer-ingressroute.yaml
- producer-ingressroute-nfl.yaml
- producer-ingressroute-mlb.yaml