apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- producer-football-ncaa-worker.yaml
- producer-football-ncaa-ingest.yaml
- producer-football-ncaa-api.yaml
- producer-football-ncaa-service.yaml
- servicemonitor.yaml
- scaledobject.yaml
- row-count-cronjob.yaml
- producer-ingressroute.yaml