apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: producer-baseball-mlb-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`producer.baseball-mlb.sportdeets.com`)
      kind: Rule
      services:
        - name: producer-svc-baseball-mlb
          port: 80
  tls:
    secretName: producer-baseball-mlb-sportdeets-tls
