apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: producer-football-ncaa-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`producer.football-ncaa.sportdeets.com`)
      kind: Rule
      services:
        - name: producer-svc-football-ncaa
          port: 80
  tls:
    secretName: producer-sportdeets-tls
