apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: producer-football-ncaa-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: producer-football-ncaa
  pollingInterval: 15    # Check every 15 seconds
  cooldownPeriod: 300    # Wait 5 min before scaling down
  minReplicaCount: 6     # TEMP: Locked during load test to prevent oscillation
  maxReplicaCount: 7     # TEMP: Locked during load test to prevent oscillation
  triggers:
    - type: postgresql
      metadata:
        # Query Hangfire database for pending jobs
        query: >-
          SELECT COUNT(*)::int
          FROM hangfire.jobqueue
          WHERE fetchedat IS NULL
            AND queue = 'default'
        targetQueryValue: "10"                # Scale up if >10 jobs per pod
        activationTargetQueryValue: "1"       # Scale from minReplicas if any jobs
      authenticationRef:
        name: producer-hangfire-trigger-auth
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: producer-hangfire-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: producer-hangfire-pg-params
      key: host
    - parameter: port
      name: producer-hangfire-pg-params
      key: port
    - parameter: userName
      name: producer-hangfire-pg-params
      key: username
    - parameter: password
      name: producer-hangfire-pg-params
      key: password
    - parameter: dbName
      name: producer-hangfire-pg-params
      key: database
    - parameter: sslmode
      name: producer-hangfire-pg-params
      key: sslmode
