apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redisinsight-deployment.yaml
- redisinsight-service.yaml
- redisinsight-ingressroute.yaml
- redisinsight-basicauth-middleware.yaml
