apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: sportsdatanotification:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: APPCONFIG_CONNSTR
            valueFrom:
              secretKeyRef:
                name: az-app-config
                key: connectionstring
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"