apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: shovel-contest-start-time-updated-nfl-to-api
  namespace: messaging
spec:
  name: shovel-contest-start-time-updated-nfl-to-api
  uriSecret:
    name: shovel-football-nfl-to-api-credentials
  srcExchange: "SportsData.Core.Eventing.Events.Contests:ContestStartTimeUpdated"
  srcExchangeKey: ""
  destExchange: "SportsData.Core.Eventing.Events.Contests:ContestStartTimeUpdated"
  ackMode: "on-confirm"
  srcPrefetchCount: 1000
  rabbitmqClusterReference:
    name: rabbitmq-api
    namespace: messaging
