resources:
  - ../../application
replicas:
- name: api
  count: 2
- name: contest
  count: 1
namespace: localdev
patches:
  - target:
      kind: Deployment
      name: api
    patch: |
      - op: replace
        path: /spec/containers/image
        value: sportdeets.azurecr.io/sportsdataapi:342
  - target:
      kind: Service
      name: api-service
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30090          