apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-ui
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: about-ui
        image: sportdeets.azurecr.io/sportsdataabout:7072
