apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-all
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: api-all
        image: sportdeets.azurecr.io/sportsdataapi:1623
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
