apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: notification
        image: sportdeets.azurecr.io/sportsdatanotification:5051
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
