apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: producer
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
