apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-football-ncaa
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: producer
        image: sportdeets.azurecr.io/sportsdataproducer:3013
        resources:
          requests:
            memory: 1Gi
            cpu: "0.5"
          limits:
            memory: 2Gi
            cpu: "2"
