apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-baseball-mlb-ingest
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: enabled
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-04-08T11:30:00Z"
    spec:
      containers:
      - name: producer-baseball-mlb-ingest
        image: sportdeets.azurecr.io/sportsdataproducer:3997
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
