apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-football-ncaa-ingest
  namespace: default
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: producer-football-ncaa-ingest
        image: sportdeets.azurecr.io/sportsdataproducer:3450
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
