apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-ncaa
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: provider-football-ncaa
        image: sportdeets.azurecr.io/sportsdataprovider:2881
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
        resources:
          requests:
            memory: 1Gi
            cpu: "0.5"
          limits:
            memory: 2Gi
            cpu: "2"
