apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-ncaa-ingest
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: provider-football-ncaa-ingest
        image: sportdeets.azurecr.io/sportsdataprovider:4816
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
