apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-nfl-ingest
  namespace: default
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-29T15:30:00Z"
    spec:
      containers:
      - name: provider-football-nfl-ingest
        image: sportdeets.azurecr.io/sportsdataprovider:3542
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
