apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-ncaa-api
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: provider-football-ncaa-api
        image: sportdeets.azurecr.io/sportsdataprovider:3755
        env:
        - name: APPCONFIG_LABEL
          value: "Prod"
