apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-metrics
  namespace: default
  labels:
    app: api-all
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-all
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
