apiVersion: v1
kind: Service
metadata:
  name: player-svc
  namespace: default
spec:
  selector:
    app: player
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: player-svc-db
  namespace: default
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: player-svc-db
    port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: player-svc-db
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - port: 1433
        name: player-svc-db