apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: local
spec:
  replicas: 0
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
      - name: prometheus
        image: prom/blackbox-exporter:v0.23.0
        imagePullPolicy: Never
        command: ["--config.file=/etc/blackbox/blackbox.yml"]
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
        ports:
        - containerPort: 9115
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"