apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  namespace: local
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30083
  type: NodePort