
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: local
data:
  prometheus.yml: |
    global:
    scrape_interval: 5s
    scrape_configs:
      - job_name: 'blackbox'    
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs:
          - targets: [ 'http://api-svc/health' ]
            labels:
              service: 'API'
          - targets: [ 'http://contest-svc/api/health' ]
            labels:
              service: 'Contest'
          - targets: [ 'http://franchise-svc/api/health' ]
            labels:
              service: 'Franchise'
          - targets: [ 'http://notification-svc/api/health' ]
            labels:
              service: 'Notification'
          - targets: [ 'http://player-svc/api/health' ]
            labels:
              service: 'Player'
          - targets: [ 'http://producer-svc/api/health' ]
            labels:
              service: 'Producer'
          - targets: [ 'http://provider-svc/api/health' ]
            labels:
              service: 'Provider'
          - targets: [ 'http://season-svc/api/health' ]
            labels:
              service: 'Season'
          - targets: [ 'http://venue-svc/api/health' ]
            labels:
              service: 'Venue'
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox:9115
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['otel-collector:8889']
        - targets: ['otel-collector:8888']