apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local
resources:
- ../../base/deployments
- ../../base/services
- ./namespace.yaml
# configMapGenerator:
#   - name: ASPNETCORE_ENVIRONMENT
#     envs:
#       - "Local"