apiVersion: apps/v1
kind: Deployment
metadata:
  name: venue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venue
  template:
    metadata:
      labels:
        app: venue
    spec:
      containers:
      - name: venue
        image: sportsdatavenue:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"