apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest
  template:
    metadata:
      labels:
        app: contest
    spec:
      containers:
      - name: contest
        image: sportsdatacontest:latest
        imagePullPolicy: Never
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"