apiVersion: apps/v1
kind: Deployment
metadata:
  name: franchise
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: franchise
  template:
    metadata:
      labels:
        app: franchise
    spec:
      containers:
      - name: franchise
        image: sportsdatafranchise:latest
        imagePullPolicy: Never
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"