apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: sportsdatanotification:latest
        imagePullPolicy: Never
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
          - name: APPCONFIG_CONNSTR
            value: "Endpoint=https://sportsdataappconfig.azconfig.io;Id=SNrN;Secret=GEZfgvYgDUQgvlL4r6UZT4pcempHRcPZ2qTQT6UJS6GqQ7ooHAvdJQQJ99BAACHYHv6VhdrZAAACAZAC21CD"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"