apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel
  namespace: local
spec:
  replicas: 0
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
      - name: otel
        image: otel/opentelemetry-collector-contrib:0.75.0
        imagePullPolicy: Never
        command: ["--config=/etc/otel-collector-config.yaml"]
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420