apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-football-ncaa
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-football-ncaa
  template:
    metadata:
      labels:
        app: producer-football-ncaa
    spec:
      containers:
      - name: producer-football-ncaa
        image: sportsdataproducer:latest
        imagePullPolicy: Never
        command: ["dotnet"]
        args: ["SportsData.Producer.dll", "-mode", "FootballNcaa"]
        env:
          - name: APPCONFIG_CONNSTR
            valueFrom:
              secretKeyRef:
                name: az-app-config
                key: connectionstring
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"