apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-football-ncaa
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-football-ncaa
  template:
    metadata:
      labels:
        app: provider-football-ncaa
    spec:
      containers:
      - name: provider-football-ncaa
        image: sportsdataprovider:latest
        imagePullPolicy: Never
        command: ["dotnet"]
        args: ["SportsData.Provider.dll", "-mode", "FootballNcaa"]
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Local"
          - name: APPCONFIG_CONNSTR
            value: "Endpoint=https://sportsdataappconfig.azconfig.io;Id=SNrN;Secret=GEZfgvYgDUQgvlL4r6UZT4pcempHRcPZ2qTQT6UJS6GqQ7ooHAvdJQQJ99BAACHYHv6VhdrZAAACAZAC21CD"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"