apiVersion: apps/v1
kind: Deployment
metadata:
  name: season
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: season
  template:
    metadata:
      labels:
        app: season
    spec:
      containers:
      - name: season
        image: sportsdataseason:latest
        imagePullPolicy: Never
        env:
          - name: APPCONFIG_CONNSTR
            valueFrom:
              secretKeyRef:
                name: az-app-config
                key: connectionstring
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"