apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: '1.10.x'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
