apiVersion: v1
kind: Service
metadata:
  name: seq-svc
  namespace: default
spec:
  selector:
    app: seq
  ports:
  - name: http
    protocol: TCP
    port: 5341
    targetPort: 5341
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: seq-ui
  namespace: default
spec:
  selector:
    app: seq
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort