apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-driver-smb
      version: "v1.19.0"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      replicas: 1
