apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    type: smb
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: logs-volume
    volumeAttributes:
      source: "//192.168.0.3/sdprod-backups/logs"
    nodeStageSecretRef:
      name: smb-creds
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: logs-pv
  storageClassName: ""
