apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest
  template:
    metadata:
      labels:
        app: contest
    spec:
      containers:
      - name: contest
        image: sportsdatacontest:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: APPCONFIG_CONNSTR
            valueFrom:
              secretKeyRef:
                name: az-app-config
                key: connectionstring
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"