apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-create-user
  namespace: messaging
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for RabbitMQ to be ready..."
              until nc -z rabbitmq.messaging.svc.cluster.local 5672; do
                echo "RabbitMQ not ready yet, sleeping..."
                sleep 5
              done
              echo "RabbitMQ is ready!"
              sleep 10
      containers:
        - name: create-user
          image: curlimages/curl:8.11.1
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-admin
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-admin
                  key: password
            - name: DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          command:
            - sh
            - -c
            - |
              echo "Creating user $RABBITMQ_USERNAME via HTTP API..."
              
              # Create user with password hash
              HASH=$(echo -n "$RABBITMQ_PASSWORD" | base64 | tr -d '\n' | base64)
              
              curl -u "$DEFAULT_USER:$DEFAULT_PASS" \
                -X PUT \
                -H "Content-Type: application/json" \
                -d "{\"password\":\"$RABBITMQ_PASSWORD\",\"tags\":\"administrator\"}" \
                http://rabbitmq.messaging.svc.cluster.local:15672/api/users/$RABBITMQ_USERNAME
              
              echo ""
              echo "Setting permissions for $RABBITMQ_USERNAME..."
              
              curl -u "$DEFAULT_USER:$DEFAULT_PASS" \
                -X PUT \
                -H "Content-Type: application/json" \
                -d '{"configure":".*","write":".*","read":".*"}' \
                http://rabbitmq.messaging.svc.cluster.local:15672/api/permissions/%2F/$RABBITMQ_USERNAME
              
              echo ""
              echo "User $RABBITMQ_USERNAME created successfully!"
