apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-create-user
  namespace: messaging
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for RabbitMQ to be ready..."
              until nc -z rabbitmq.messaging.svc.cluster.local 5672; do
                echo "RabbitMQ not ready yet, sleeping..."
                sleep 5
              done
              echo "RabbitMQ is ready!"
              sleep 10
      containers:
        - name: create-user
          image: rabbitmq:3.13-management
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-admin
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-admin
                  key: password
          command:
            - sh
            - -c
            - |
              echo "Creating user $RABBITMQ_USERNAME..."
              
              # Delete user if exists (idempotent)
              rabbitmqadmin -H rabbitmq.messaging.svc.cluster.local -u $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) delete user name=$RABBITMQ_USERNAME 2>/dev/null || true
              
              # Create user
              rabbitmqctl -n rabbit@rabbitmq-server-0.rabbitmq-nodes.messaging add_user "$RABBITMQ_USERNAME" "$RABBITMQ_PASSWORD" || echo "User may already exist"
              
              # Set admin tag
              rabbitmqctl -n rabbit@rabbitmq-server-0.rabbitmq-nodes.messaging set_user_tags "$RABBITMQ_USERNAME" administrator
              
              # Grant permissions
              rabbitmqctl -n rabbit@rabbitmq-server-0.rabbitmq-nodes.messaging set_permissions -p / "$RABBITMQ_USERNAME" ".*" ".*" ".*"
              
              echo "User $RABBITMQ_USERNAME created successfully!"
