apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: messaging
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: '4.x'
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
        namespace: flux-system
      interval: 1m
  values:
    # Single replica for operator is fine
    replicaCount: 1
    
    # Resource limits for operator
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
