apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - namespace.yaml
  - rabbitmq-cluster.yaml
  - rabbitmq-cluster-nfl.yaml
  - rabbitmq-cluster-mlb.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
