apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - namespace.yaml
  - rabbitmq-cluster-api.yaml
  - rabbitmq-cluster-baseball-mlb.yaml
  - rabbitmq-cluster-football-ncaa.yaml
  - rabbitmq-cluster-football-nfl.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
  - shovels
