apiVersion: v1
kind: Service
metadata:
  name: cache-svc
  namespace: local
spec:
  selector:
    app: redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cache-ui
  namespace: local
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30082
  type: NodePort