apiVersion: v1
kind: Service
metadata:
  name: contest-svc
  namespace: local
spec:
  selector:
    app: contest
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
# https://stackoverflow.com/questions/63344920/access-external-database-from-kubernetes
# https://stackoverflow.com/questions/65123401/how-to-access-hosts-localhost-from-inside-kubernetes-cluster
apiVersion: v1
kind: Service
metadata:
  name: contest-svc-db
  namespace: local
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: contest-svc-db
    port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: contest-svc-db
  namespace: local
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - port: 1433
        name: contest-svc-db