apiVersion: v1
kind: Service
metadata:
  name: franchise-svc
  namespace: local
spec:
  selector:
    app: franchise
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: franchise-svc-db
  namespace: local
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: franchise-svc-db
    port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: franchise-svc-db
  namespace: local
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - port: 1433
        name: franchise-svc-db