apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: local
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30084
  type: NodePort