apiVersion: v1
kind: Service
metadata:
  name: provider-svc
  namespace: local
spec:
  selector:
    app: provider
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
#MSSQL
apiVersion: v1
kind: Service
metadata:
  name: provider-svc-db
  namespace: local
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: provider-svc-db
    port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: provider-svc-db
  namespace: local
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - port: 1433
        name: provider-svc-db
---
# MongoDb
apiVersion: v1
kind: Service
metadata:
  name: provider-svc-doc-db
  namespace: local
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: provider-svc-doc-db
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: provider-svc-doc-db
  namespace: local
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - port: 27017
        name: provider-svc-doc-db