apiVersion: v1
kind: Service
metadata:
  name: provider-svc-football-nfl
  namespace: local
spec:
  selector:
    app: provider-football-nfl
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
#MSSQL
apiVersion: v1
kind: Service
metadata:
  name: provider-svc-football-nfl-db
  namespace: local
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    name: provider-svc-football-nfl-db
    port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: provider-svc-football-nfl-db
  namespace: local
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - port: 1433
        name: provider-svc-football-nfl-db
# ---
# # MongoDb
# apiVersion: v1
# kind: Service
# metadata:
#   name: provider-svc-football-nfl-doc-db
#   namespace: local
# spec:
#   clusterIP: None
#   ports:
#   - protocol: TCP
#     name: provider-svc-football-nfl-doc-db
#     port: 27017
#     targetPort: 27017
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Endpoints
# metadata:
#   name: provider-svc-football-nfl-doc-db
#   namespace: local
# subsets:
#   - addresses:
#       - ip: 192.168.0.3
#     ports:
#       - port: 27017
#         name: provider-svc-football-nfl-doc-db