apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama-service
  namespace: default
subsets:
  - addresses:
      - ip: OLLAMA_HOST_IP  # Placeholder - replaced by overlay
    ports:
      - port: 11434
