apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: localdev
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30090
  type: NodePort