apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: localdev
spec:
  selector:
    app: notification
  ports:
  - name: http
    protocol: TCP
    port: 8080
  clusterIP: None